[package]
name = "polkadot-node-core-backing"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.5"
sp-keystore = { git = "https://github.com/mxinden/substrate", branch = "libp2p-v0.30.0" }
polkadot-primitives = { path = "../../../primitives" }
polkadot-node-primitives = { path = "../../primitives" }
polkadot-subsystem = { package = "polkadot-node-subsystem", path = "../../subsystem" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
erasure-coding = { package = "polkadot-erasure-coding", path = "../../../erasure-coding" }
statement-table = { package = "polkadot-statement-table", path = "../../../statement-table" }
bitvec = { version = "0.17.4", default-features = false, features = ["alloc"] }
log = "0.4.11"
thiserror = "1.0.21"

[dev-dependencies]
sp-core = { git = "https://github.com/mxinden/substrate", branch = "libp2p-v0.30.0" }
sp-application-crypto = { git = "https://github.com/mxinden/substrate", branch = "libp2p-v0.30.0" }
sp-keyring = { git = "https://github.com/mxinden/substrate", branch = "libp2p-v0.30.0" }
sc-keystore = { git = "https://github.com/mxinden/substrate", branch = "libp2p-v0.30.0" }
futures = { version = "0.3.5", features = ["thread-pool"] }
assert_matches = "1.3.0"
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
