[package]
name = "polkadot-availability-distribution"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.22"
tracing-futures = "0.2.4"
parity-scale-codec = { version = "2.0.0", features = ["std"]  }
polkadot-primitives = { path = "../../../primitives" }
polkadot-erasure-coding = { path = "../../../erasure-coding" }
polkadot-subsystem = { package = "polkadot-node-subsystem", path = "../../subsystem" }
polkadot-node-network-protocol = { path = "../../network/protocol" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
sp-core = { git = "https://github.com/paritytech/substrate", features = ["std"]  , branch = "td-mmr-custom" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "td-mmr-custom" }
thiserror = "1.0.23"

[dev-dependencies]
polkadot-subsystem-testhelpers = { package = "polkadot-node-subsystem-test-helpers", path = "../../subsystem-test-helpers" }
sp-core = { git = "https://github.com/paritytech/substrate", features = ["std"] , branch = "td-mmr-custom" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "td-mmr-custom" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "td-mmr-custom" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "td-mmr-custom" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "td-mmr-custom" }
assert_matches = "1.4.0"
maplit = "1.0"
