[package]
name = "polkadot-primitives"
version = "0.8.27"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.118", optional = true, features = ["derive"] }
parity-scale-codec = { version = "1.3.5", default-features = false, features = ["bit-vec", "derive"] }
primitives = { package = "sp-core", git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-sync-update-common-block" }
inherents = { package = "sp-inherents", git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-sync-update-common-block" }
application-crypto = { package = "sp-application-crypto", git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-sync-update-common-block" }
sp-keystore = { git = "https://github.com/paritytech/substrate", optional = true , branch = "bkchr-sync-update-common-block" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-sync-update-common-block" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-sync-update-common-block" }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-sync-update-common-block" }
sp-staking = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-sync-update-common-block" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-sync-update-common-block" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-sync-update-common-block" }
runtime_primitives = { package = "sp-runtime", git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-sync-update-common-block" }
polkadot-parachain = { path = "../parachain", default-features = false }
polkadot-core-primitives = { path = "../core-primitives", default-features = false }
trie = { package = "sp-trie", git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-sync-update-common-block" }
bitvec = { version = "0.17.4", default-features = false, features = ["alloc"] }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-sync-update-common-block" }

[dev-dependencies]
sp-serializer = { git = "https://github.com/paritytech/substrate", branch = "bkchr-sync-update-common-block" }
pretty_assertions = "0.6.1"

[features]
default = ["std"]
std = [
	"application-crypto/std",
	"parity-scale-codec/std",
	"primitives/std",
	"inherents/std",
	"trie/std",
	"sp-api/std",
	"sp-authority-discovery/std",
	"sp-keystore",
	"sp-std/std",
	"sp-version/std",
	"sp-staking/std",
	"sp-arithmetic/std",
	"runtime_primitives/std",
	"serde",
	"polkadot-parachain/std",
	"polkadot-core-primitives/std",
	"bitvec/std",
	"frame-system/std",
]
