[package]
name = "polkadot-statement-distribution"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Statement Distribution Subsystem"
edition = "2018"

[dependencies]
futures = "0.3.15"
tracing = "0.1.26"
polkadot-primitives = { path = "../../../primitives" }
sp-staking = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-ocw-max-heap-pages" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "kiz-ocw-max-heap-pages" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "kiz-ocw-max-heap-pages" }
polkadot-subsystem = { package = "polkadot-node-subsystem", path = "../../subsystem" }
polkadot-node-primitives = { path = "../../primitives" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-node-network-protocol = { path = "../../network/protocol" }
arrayvec = "0.5.2"
indexmap = "1.7.0"
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
thiserror = "1.0.23"

[dev-dependencies]
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
assert_matches = "1.4.0"
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "kiz-ocw-max-heap-pages" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "kiz-ocw-max-heap-pages" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "kiz-ocw-max-heap-pages" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "kiz-ocw-max-heap-pages" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "kiz-ocw-max-heap-pages" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "kiz-ocw-max-heap-pages" }
futures-timer = "3.0.2"
