[package]
name = "polkadot-rpc"
version = "0.6.6"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
client = { package = "substrate-client", git = "https://github.com/paritytech/substrate", branch = "ben-make-config-path-usage-reusable-for-services" }
jsonrpc-core = "13.2.0"
polkadot-primitives = { path = "../primitives" }
sr-primitives = { git = "https://github.com/paritytech/substrate", branch = "ben-make-config-path-usage-reusable-for-services"  }
substrate-rpc = { git = "https://github.com/paritytech/substrate", branch = "ben-make-config-path-usage-reusable-for-services" }
transaction_pool = { package = "substrate-transaction-pool", git = "https://github.com/paritytech/substrate", branch = "ben-make-config-path-usage-reusable-for-services"  }
srml-system-rpc = { git = "https://github.com/paritytech/substrate", branch = "ben-make-config-path-usage-reusable-for-services"  }
srml-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "ben-make-config-path-usage-reusable-for-services" }
polkadot-runtime = { path = "../runtime" }

