[package]
name = "polkadot-rpc"
version = "0.6.17"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
client = { package = "substrate-client", git = "https://github.com/paritytech/substrate", branch = "master" }
jsonrpc-core = "14.0.3"
polkadot-primitives = { path = "../primitives" }
sr-primitives = { git = "https://github.com/paritytech/substrate", branch = "master"  }
substrate-rpc = { git = "https://github.com/paritytech/substrate", branch = "master" }
transaction_pool = { package = "sc-transaction-pool", git = "https://github.com/paritytech/substrate", branch = "master"  }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "master"  }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "master" }
polkadot-runtime = { path = "../runtime" }

