[package]
name = "polkadot-rpc"
version = "0.6.14"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
client = { package = "substrate-client", git = "https://github.com/paritytech/substrate", branch = "v0.6.14" }
jsonrpc-core = "14.0.3"
polkadot-primitives = { path = "../primitives" }
sr-primitives = { git = "https://github.com/paritytech/substrate", branch = "v0.6.14"  }
substrate-rpc = { git = "https://github.com/paritytech/substrate", branch = "v0.6.14" }
transaction_pool = { package = "substrate-transaction-pool", git = "https://github.com/paritytech/substrate", branch = "v0.6.14"  }
srml-system-rpc = { git = "https://github.com/paritytech/substrate", branch = "v0.6.14"  }
srml-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "v0.6.14" }
polkadot-runtime = { path = "../runtime" }

