[package]
name = "polkadot-rpc"
version = "0.7.34-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
jsonrpc-core = "14.0.3"
polkadot-primitives = { path = "../primitives" }
sc-client-api = { git = "https://github.com/tomaka/polkadot", branch = "move-legacy-handshake"  }
sp-blockchain = { git = "https://github.com/tomaka/polkadot", branch = "move-legacy-handshake"  }
sp-runtime = { git = "https://github.com/tomaka/polkadot", branch = "move-legacy-handshake"  }
sp-api = { git = "https://github.com/tomaka/polkadot", branch = "move-legacy-handshake"  }
sp-consensus = { git = "https://github.com/tomaka/polkadot", branch = "move-legacy-handshake"  }
sp-consensus-babe = { git = "https://github.com/tomaka/polkadot", branch = "move-legacy-handshake"  }
sc-rpc = { git = "https://github.com/tomaka/polkadot", branch = "move-legacy-handshake" }
sc-consensus-babe = { git = "https://github.com/tomaka/polkadot", branch = "move-legacy-handshake"}
sc-consensus-babe-rpc = { git = "https://github.com/tomaka/polkadot", branch = "move-legacy-handshake"}
sc-consensus-epochs = { git = "https://github.com/tomaka/polkadot", branch = "move-legacy-handshake"}
sc-finality-grandpa = { git = "https://github.com/tomaka/polkadot", branch = "move-legacy-handshake" }
sc-finality-grandpa-rpc = { git = "https://github.com/tomaka/polkadot", branch = "move-legacy-handshake" }
sc-keystore = { git = "https://github.com/tomaka/polkadot", branch = "move-legacy-handshake"}
txpool-api = { package = "sp-transaction-pool", git = "https://github.com/tomaka/polkadot", branch = "move-legacy-handshake" }
frame-rpc-system = { package = "substrate-frame-rpc-system", git = "https://github.com/tomaka/polkadot", branch = "move-legacy-handshake"  }
pallet-transaction-payment-rpc = { git = "https://github.com/tomaka/polkadot", branch = "move-legacy-handshake" }
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false }
