[package]
name = "polkadot-gossip-support"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "kiz-polkadot-v930-rpc-patched" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "kiz-polkadot-v930-rpc-patched" }

polkadot-node-network-protocol = { path = "../protocol" }
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-primitives = { path = "../../../primitives" }

futures = "0.3.8"
tracing = "0.1.25"

[dev-dependencies]
sp-core = { git = "https://github.com/paritytech/substrate", features = ["std"] , branch = "kiz-polkadot-v930-rpc-patched" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "kiz-polkadot-v930-rpc-patched" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "kiz-polkadot-v930-rpc-patched" }

polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }

assert_matches = "1.4.0"
