[package]
name = "polkadot-runtime-common"
version = "0.9.8"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
impl-trait-for-tuples = "0.2.0"
bitvec = { version = "0.20.1", default-features = false, features = ["alloc"] }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4.13", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }
serde = { version = "1.0.123", default-features = false }
serde_derive = { version = "1.0.117", optional = true }
static_assertions = "1.1.0"

sp-api = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
inherents = { package = "sp-inherents", git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
sp-session = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
sp-staking = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }

pallet-authorship = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
pallet-session = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
pallet-staking = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
frame-system = {git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
pallet-vesting = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
pallet-offences = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
pallet-treasury = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
pallet-election-provider-multi-phase = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }
pallet-beefy-mmr = { git = "https://github.com/paritytech/grandpa-bridge-gadget", branch = "bkchr-statemine-fix", default-features = false }

frame-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true , branch = "bkchr-statemine-fix" }
pallet-babe = { git = "https://github.com/paritytech/substrate", default-features=false, optional = true , branch = "bkchr-statemine-fix" }

primitives = { package = "polkadot-primitives", path = "../../primitives", default-features = false }
libsecp256k1 = { version = "0.3.5", default-features = false }
runtime-parachains = { package = "polkadot-runtime-parachains", path = "../parachains", default-features = false }

slot-range-helper = { path = "slot_range_helper", default-features = false }
xcm = { path = "../../xcm", default-features = false }

[dev-dependencies]
hex-literal = "0.3.1"
keyring = { package = "sp-keyring", git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
frame-support-test = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
pallet-babe = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
pallet-staking-reward-curve = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
pallet-treasury = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
trie-db = "0.22.3"
serde_json = "1.0.61"
libsecp256k1 = "0.3.5"

[features]
default = ["std"]
no_std = []
std = [
	"bitvec/std",
	"parity-scale-codec/std",
	"log/std",
	"rustc-hex/std",
	"serde_derive",
	"serde/std",
	"primitives/std",
	"inherents/std",
	"sp-core/std",
	"sp-api/std",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-beefy-mmr/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-timestamp/std",
	"pallet-vesting/std",
	"pallet-transaction-payment/std",
	"pallet-treasury/std",
	"pallet-election-provider-multi-phase/std",
	"slot-range-helper/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"frame-system/std",
	"libsecp256k1/std",
	"runtime-parachains/std",
	"xcm/std",
]
runtime-benchmarks = [
	"libsecp256k1/hmac",
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"runtime-parachains/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
]
try-runtime = [
	"runtime-parachains/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-session/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-vesting/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-treasury/try-runtime",
]
