[package]
name = "relay-millau-client"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
headers-relay = { path = "../headers" }
relay-substrate-client = { path = "../client-substrate" }
relay-utils = { path = "../utils" }

# Supported Chains

millau-runtime = { path = "../../bin/millau/runtime" }

# Substrate Dependencies

frame-support = { git = "https://github.com/paritytech/substrate", branch = "kiz-buirnin-allocator" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "kiz-buirnin-allocator" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "kiz-buirnin-allocator" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "kiz-buirnin-allocator" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "kiz-buirnin-allocator" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "kiz-buirnin-allocator" }
