[package]
name = "polkadot-cli"
version = "0.8.25"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Polkadot Relay-chain Client Node"
edition = "2018"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4.8"
futures = { version = "0.3.4", features = ["compat"] }
structopt = "0.3.8"
sp-api = { git = "https://github.com/mxinden/substrate", branch = "async-std-1.6.5" }
sp-core = { git = "https://github.com/mxinden/substrate", branch = "async-std-1.6.5" }
sp-runtime = { git = "https://github.com/mxinden/substrate", branch = "async-std-1.6.5" }
sc-client-api = { git = "https://github.com/mxinden/substrate", branch = "async-std-1.6.5" }
sc-client-db = { git = "https://github.com/mxinden/substrate", branch = "async-std-1.6.5" }
sc-executor = { git = "https://github.com/mxinden/substrate", branch = "async-std-1.6.5" }
sc-tracing = { git = "https://github.com/mxinden/substrate", branch = "async-std-1.6.5" }
service = { package = "polkadot-service", path = "../node/service", default-features = false, optional = true }

tokio = { version = "0.2.13", features = ["rt-threaded"], optional = true }
frame-benchmarking-cli = { git = "https://github.com/mxinden/substrate", branch = "async-std-1.6.5", optional = true }
sc-cli = { git = "https://github.com/mxinden/substrate", branch = "async-std-1.6.5", optional = true }
sc-service = { git = "https://github.com/mxinden/substrate", branch = "async-std-1.6.5", optional = true }

wasm-bindgen = { version = "0.2.57", optional = true }
wasm-bindgen-futures = { version = "0.4.7", optional = true }
browser-utils = { package = "substrate-browser-utils", git = "https://github.com/mxinden/substrate", branch = "async-std-1.6.5", optional = true }
# this crate is used only to enable `trie-memory-tracker` feature
# see https://github.com/mxinden/substrate/pull/6745
sp-trie = { git = "https://github.com/mxinden/substrate", branch = "async-std-1.6.5", default-features = false }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/mxinden/substrate", branch = "async-std-1.6.5" }

[features]
default = [ "wasmtime", "db", "cli", "full-node", "trie-memory-tracker" ]
wasmtime = [ "sc-cli/wasmtime" ]
db = [ "service/db" ]
cli = [
	"tokio",
	"sc-cli",
	"sc-service",
	"frame-benchmarking-cli",
]
browser = [
	"wasm-bindgen",
	"wasm-bindgen-futures",
	"browser-utils",
	"service",
]
runtime-benchmarks = [ "service/runtime-benchmarks" ]
trie-memory-tracker = [ "sp-trie/memory-tracker" ]
full-node = [ "service/full-node" ]
