[package]
name = "polkadot-cli"
version = "0.7.17"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Polkadot node implementation in Rust."
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4.8"
futures = { version = "0.3.1", features = ["compat"] }
futures01 = { package = "futures", version = "0.1.29" }
structopt = "=0.3.7"
sc-cli = { git = "https://github.com/tomaka/polkadot", branch = "hack" }
sp-api = { git = "https://github.com/tomaka/polkadot", branch = "hack" }
sp-core = { git = "https://github.com/tomaka/polkadot", branch = "hack" }
sp-runtime = { git = "https://github.com/tomaka/polkadot", branch = "hack" }
sc-client = { git = "https://github.com/tomaka/polkadot", branch = "hack" }
sc-client-api = { git = "https://github.com/tomaka/polkadot", branch = "hack" }
sc-client-db = { git = "https://github.com/tomaka/polkadot", branch = "hack" }
sc-executor = { git = "https://github.com/tomaka/polkadot", branch = "hack" }
service = { package = "polkadot-service", path = "../service", default-features = false }

tokio = { version = "0.2", features = ["rt-threaded"], optional = true }

wasm-bindgen = { version = "0.2.57", optional = true }
wasm-bindgen-futures = { version = "0.4.7", optional = true }
browser-utils = { package = "browser-utils", git = "https://github.com/tomaka/polkadot", branch = "hack", optional = true }
substrate-service = { package = "sc-service", git = "https://github.com/tomaka/polkadot", branch = "hack", optional = true, default-features = false }

[features]
default = [ "wasmtime", "rocksdb", "cli" ]
wasmtime = [ "sc-cli/wasmtime" ]
rocksdb = [ "service/rocksdb" ]
cli = [ "tokio" ]
browser = [
	"wasm-bindgen",
	"wasm-bindgen-futures",
	"browser-utils",
	"substrate-service",
]
