[package]
name = "polkadot-statement-table"
version = "0.7.20"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.1.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/tomaka/polkadot", branch = "libp2p-0.16" }
primitives = { package = "polkadot-primitives", path = "../primitives" }
