[package]
name = "polkadot-statement-table"
version = "0.8.25"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/mxinden/substrate", branch = "async-std-1.6.5" }
primitives = { package = "polkadot-primitives", path = "../primitives" }
