[package]
name = "polkadot-statement-table"
version = "0.6.6"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "~1.0.0", default-features = false, features = ["derive"] }
substrate-primitives = { git = "https://github.com/paritytech/substrate", branch = "ben-make-config-path-usage-reusable-for-services" }
primitives = { package = "polkadot-primitives", path = "../primitives" }
