[package]
name = "polkadot-client"
version = "0.9.8"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }

sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
sp-storage = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
sp-offchain = { package = "sp-offchain", git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }

sc-executor = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }
sc-service = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-statemine-fix" }

pallet-mmr-primitives = { git = "https://github.com/paritytech/substrate", branch = "bkchr-statemine-fix" }

beefy-primitives = { git = "https://github.com/paritytech/grandpa-bridge-gadget", branch = "bkchr-statemine-fix" }

# Polkadot Runtimes
polkadot-runtime = { path = "../../runtime/polkadot" }
kusama-runtime = { path = "../../runtime/kusama", optional = true }
westend-runtime = { path = "../../runtime/westend", optional = true }
rococo-runtime = { path = "../../runtime/rococo", optional = true }

polkadot-primitives = { path = "../../primitives" }

[features]
kusama = [ "kusama-runtime" ]
rococo = [ "rococo-runtime" ]
westend = [ "westend-runtime" ]
