[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
name = "xcm-executor"
description = "An abstract and configurable XCM message executor."
version = "0.8.22"

[dependencies]
impl-trait-for-tuples = "0.1.3"
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
xcm = { path = "..", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "andre/grandpa-cache-round-id" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "andre/grandpa-cache-round-id" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "andre/grandpa-cache-round-id" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "andre/grandpa-cache-round-id" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "andre/grandpa-cache-round-id" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "andre/grandpa-cache-round-id" }

[features]
default = ["std"]
std = [
	"codec/std",
	"xcm/std",
	"sp-std/std",
	"sp-io/std",
	"sp-arithmetic/std",
	"sp-core/std",
	"sp-runtime/std",
	"frame-support/std",
]
