[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
name = "xcm-executor"
description = "An abstract and configurable XCM message executor."
version = "0.8.22"

[dependencies]
impl-trait-for-tuples = "0.2.0"
parity-scale-codec = { version = "1.3.5", default-features = false, features = ["derive"] }
xcm = { path = "..", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-sync-update-common-block" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-sync-update-common-block" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-sync-update-common-block" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-sync-update-common-block" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-sync-update-common-block" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "bkchr-sync-update-common-block" }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"xcm/std",
	"sp-std/std",
	"sp-io/std",
	"sp-arithmetic/std",
	"sp-core/std",
	"sp-runtime/std",
	"frame-support/std",
]
