[package]
name = "polkadot-executor"
version = "0.6.14"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Polkadot node implementation in Rust."
edition = "2018"

[dependencies]
substrate-executor = { git = "https://github.com/paritytech/substrate", branch = "v0.6.14" }
polkadot-runtime = { path = "../runtime" }
