[package]
name = "test-parachain-adder-collator"
version = "0.7.26"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Collator for the adder test parachain"
edition = "2018"

[[bin]]
name = "adder-collator"
path = "src/main.rs"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
futures = "0.3.4"
futures-timer = "3.0.2"
log = "0.4.8"
structopt = "0.3.8"

test-parachain-adder = { path = ".." }
polkadot-primitives = { path = "../../../../primitives" }
polkadot-cli = { path = "../../../../cli" }
polkadot-service = { path = "../../../../node/service" }
polkadot-node-primitives = { path = "../../../../node/primitives" }
polkadot-node-subsystem = { path = "../../../../node/subsystem" }

sc-cli = { git = "https://github.com/mxinden/substrate", branch = "libp2p-v0.30.0" }
sp-core = { git = "https://github.com/mxinden/substrate", branch = "libp2p-v0.30.0" }
sc-authority-discovery = { git = "https://github.com/mxinden/substrate", branch = "libp2p-v0.30.0" }

[dev-dependencies]
polkadot-parachain = { path = "../../.." }
polkadot-test-service = { path = "../../../../node/test/service" }

substrate-test-utils = { git = "https://github.com/mxinden/substrate", branch = "libp2p-v0.30.0" }
sc-service = { git = "https://github.com/mxinden/substrate", branch = "libp2p-v0.30.0" }
sp-keyring = { git = "https://github.com/mxinden/substrate", branch = "libp2p-v0.30.0" }

tokio = { version = "0.2", features = ["macros"] }

[features]
real-overseer = [ "polkadot-service/real-overseer" ]
