[lib]
name = "malus"
path = "src/lib.rs"

[[bin]]
name = "malus-suggest-garbage-candidate"
path = "src/malus-suggest-garbage-candidate.rs"

[[bin]]
name = "malus-back-garbage-candidate"
path = "src/malus-back-garbage-candidate.rs"


[package]
name = "polkadot-test-malus"
description = "Misbehaving nodes for local testnets, system and Simnet tests."
license = "GPL-3.0-only"
version = "0.9.9"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
readme = "README.md"
publish = false

[dependencies]
polkadot-cli = { path = "../../cli", default-features = false, features = [ "cli", "malus" ]  }
polkadot-node-subsystem = { path = "../subsystem" }
polkadot-node-subsystem-util = { path = "../subsystem-util" }
polkadot-node-subsystem-types = { path = "../subsystem-types" }
polkadot-node-core-dispute-coordinator = { path = "../core/dispute-coordinator"}
polkadot-node-core-candidate-validation = { path = "../core/candidate-validation"}
polkadot-node-core-backing = { path = "../core/backing" }
polkadot-primitives = { path = "../../primitives" }
parity-util-mem = { version = "0.10.0", default-features = false, features = ["jemalloc-global"] }
color-eyre = { version = "0.5.11", default-features = false }
assert_matches = "1.5"
structopt = "0.3.21"
async-trait = "0.1.50"
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "master" }
tracing = "0.1.26"
